// Police stations and live patrolling units inside Raipur Police Commissionerate boundary.
// Landmark coordinates verified against OpenStreetMap (OSM) nodes.

export const PATROL_AREAS = [
  {
    id: "all",
    name: "सभी क्षेत्र (All Areas)",
    nameEn: "All Raipur Sectors (Citywide)",
    center: [21.2460, 81.6360],
    zoom: 12,
    description: "समस्त 8 पेट्रोलिंग सेक्टर व सभी गश्त वाहन",
    descriptionEn: "All 8 patrol sectors & citywide fleet",
    color: "#1e3a8a",
  },
  {
    id: "kotwali",
    name: "सेंट्रल सेक्टर — कोतवाली व गोल बाज़ार",
    nameEn: "Central Sector — Kotwali & Gol Bazar",
    center: [21.2435, 81.6350],
    zoom: 14,
    description: "जयस्तंभ चौक, मालवीय रोड, सदर बाज़ार, गोल बाज़ार",
    descriptionEn: "Jaistambh Chowk, Malviya Road, Sadar Bazar, Gol Bazar",
    color: "#b91c1c",
    polygon: [
      [21.2500, 81.6250],
      [21.2520, 81.6420],
      [21.2380, 81.6430],
      [21.2360, 81.6270],
    ],
  },
  {
    id: "civil-lines",
    name: "वीआईपी सेक्टर — सिविल लाइन्स व घड़ी चौक",
    nameEn: "VIP Sector — Civil Lines & Ghadi Chowk",
    center: [21.2455, 81.6430],
    zoom: 14,
    description: "कलेक्टोरेट, राजभवन, पुलिस ग्राउंड, शांति नगर",
    descriptionEn: "Collectorate, Raj Bhavan, Police Ground, Shanti Nagar",
    color: "#1d4ed8",
    polygon: [
      [21.2550, 81.6380],
      [21.2560, 81.6550],
      [21.2390, 81.6560],
      [21.2380, 81.6390],
    ],
  },
  {
    id: "telibandha",
    name: "ईस्ट सेक्टर — तेलीबांधा व मरीन ड्राइव",
    nameEn: "East Sector — Telibandha & Marine Drive",
    center: [21.2365, 81.6715],
    zoom: 14,
    description: "मरीन ड्राइव, वीआईपी रोड, लाभांडी, तेलीबांधा तालाब",
    descriptionEn: "Marine Drive, VIP Road, Labhandi, Telibandha Lake",
    color: "#059669",
    polygon: [
      [21.2480, 81.6600],
      [21.2490, 81.6880],
      [21.2220, 81.6850],
      [21.2230, 81.6580],
    ],
  },
  {
    id: "pandri",
    name: "कमर्शियल सेक्टर — पंडरी व देवेन्द्र नगर",
    nameEn: "Commercial Sector — Pandri & Devendra Nagar",
    center: [21.2530, 81.6470],
    zoom: 14,
    description: "पंडरी बस स्टैंड, कपड़ा बाज़ार, मोवा, सिटी सेंटर मॉल",
    descriptionEn: "Pandri Bus Stand, Cloth Market, Mowa, City Center Mall",
    color: "#d97706",
    polygon: [
      [21.2650, 81.6380],
      [21.2660, 81.6600],
      [21.2480, 81.6590],
      [21.2470, 81.6370],
    ],
  },
  {
    id: "saraswati-nagar",
    name: "वेस्ट सेक्टर — सरस्वती नगर व एनआईटी",
    nameEn: "West Sector — Saraswati Nagar & NIT",
    center: [21.2510, 81.5910],
    zoom: 14,
    description: "एनआईटी रायपुर, यूनिवर्सिटी रोड, समता कॉलोनी, आमानाका",
    descriptionEn: "NIT Raipur, University Road, Samta Colony, Amanaka",
    color: "#7c3aed",
    polygon: [
      [21.2620, 81.5780],
      [21.2630, 81.6050],
      [21.2400, 81.6030],
      [21.2390, 81.5790],
    ],
  },
  {
    id: "tikrapara",
    name: "साउथ सेक्टर — टिकरापारा व पचपेड़ी नाका",
    nameEn: "South Sector — Tikrapara & Pachpedi Naka",
    center: [21.2240, 81.6520],
    zoom: 14,
    description: "पचपेड़ी नाका, संतोषी नगर, पुरानी धमतरी रोड, रिंग रोड 1",
    descriptionEn: "Pachpedi Naka, Santoshi Nagar, Old Dhamtari Rd, Ring Road 1",
    color: "#dc2626",
    polygon: [
      [21.2340, 81.6400],
      [21.2350, 81.6660],
      [21.2100, 81.6640],
      [21.2090, 81.6380],
    ],
  },
  {
    id: "tatibandh",
    name: "हाईवे सेक्टर — तातीबंध व एम्स अस्पताल",
    nameEn: "Highway Sector — Tatibandh & AIIMS",
    center: [21.2580, 81.5750],
    zoom: 14,
    description: "तातीबंध चौक, एम्स अस्पताल, एनएच-53 हाईवे बाइपास",
    descriptionEn: "Tatibandh Chowk, AIIMS Hospital, NH-53 Highway Bypass",
    color: "#0891b2",
    polygon: [
      [21.2720, 81.5600],
      [21.2730, 81.5880],
      [21.2480, 81.5870],
      [21.2470, 81.5590],
    ],
  },
  {
    id: "ganj",
    name: "स्टेशन सेक्टर — गंज व रेलवे स्टेशन",
    nameEn: "Station Sector — Ganj & Railway Station",
    center: [21.2570, 81.6290],
    zoom: 14,
    description: "रायपुर रेलवे जंक्शन, स्टेशन रोड, फाफाडीह, रामसागर पारा",
    descriptionEn: "Raipur Railway Junction, Station Road, Fafadih, Ramsagar Para",
    color: "#4f46e5",
    polygon: [
      [21.2680, 81.6200],
      [21.2690, 81.6380],
      [21.2490, 81.6370],
      [21.2480, 81.6190],
    ],
  },
];

export const POLICE_STATIONS = [
  {
    id: "kotwali-ps",
    type: "station",
    code: "PS-KTW",
    name: "कोतवाली पुलिस थाना",
    nameEn: "Kotwali Police Station",
    areaId: "kotwali",
    lat: 21.24350,
    lng: 81.63500,
    phone: "0771-4287111",
    emergencyPhone: "112 / 0771-4287111",
    inCharge: "Ins. R. K. Sharma",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "सेंट्रल मार्केट, जयस्तंभ चौक, मालवीय रोड, गोल बाज़ार",
    jurisdictionEn: "Central Market, Jaistambh Chowk, Malviya Road, Gol Bazar",
    address: "गोल बाज़ार के पास, कोतवाली चौक, रायपुर",
    addressEn: "Near Gol Bazar, Kotwali Chowk, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-01 (Kotwali Tiger)",
    pcrId: "patrol-kotwali-01",
  },
  {
    id: "civil-lines-ps",
    type: "station",
    code: "PS-CVL",
    name: "सिविल लाइन्स पुलिस थाना",
    nameEn: "Civil Lines Police Station",
    areaId: "civil-lines",
    lat: 21.24491,
    lng: 81.64450,
    phone: "0771-4287122",
    emergencyPhone: "112 / 0771-4287122",
    inCharge: "Ins. V. P. Singh",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "कलेक्टोरेट, घड़ी चौक, राज भवन, सिविल लाइन्स, पुलिस ग्राउंड",
    jurisdictionEn: "Collectorate, Ghadi Chowk, Raj Bhavan, Civil Lines, Police Ground",
    address: "कलेक्टोरेट परिसर के सामने, सिविल लाइन्स, रायपुर",
    addressEn: "Opposite Collectorate Complex, Civil Lines, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-02 (Civil Lines Hawk)",
    pcrId: "patrol-civillines-02",
  },
  {
    id: "telibandha-ps",
    type: "station",
    code: "PS-TLB",
    name: "तेलीबांधा पुलिस थाना",
    nameEn: "Telibandha Police Station",
    areaId: "telibandha",
    lat: 21.23650,
    lng: 81.67150,
    phone: "0771-4287133",
    emergencyPhone: "112 / 0771-4287133",
    inCharge: "Ins. A. K. Verma",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "तेलीबांधा चौक, जीई रोड, वीआईपी रोड, मरीन ड्राइव (तेलीबांधा तालाब)",
    jurisdictionEn: "Telibandha Chowk, GE Road, VIP Road, Marine Drive",
    address: "मरीन ड्राइव मुख्य मार्ग, तेलीबांधा, रायपुर",
    addressEn: "Marine Drive Main Road, Telibandha, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-03 (Telibandha Eagle)",
    pcrId: "patrol-telibandha-03",
  },
  {
    id: "pandri-ps",
    type: "station",
    code: "PS-PND",
    name: "पंडरी / देवेन्द्र नगर पुलिस थाना",
    nameEn: "Pandri / Devendra Nagar Police Station",
    areaId: "pandri",
    lat: 21.25300,
    lng: 81.64700,
    phone: "0771-4287144",
    emergencyPhone: "112 / 0771-4287144",
    inCharge: "Ins. S. N. Mishra",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "पंडरी बस स्टैंड, कपड़ा बाज़ार, देवेन्द्र नगर, मोवा, सिटी मॉल",
    jurisdictionEn: "Pandri Bus Stand, Cloth Market, Devendra Nagar, Mowa, City Mall",
    address: "सिटी सेंटर मॉल के समीप, पंडरी रोड, रायपुर",
    addressEn: "Near City Center Mall, Pandri Road, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-04 (Pandri Cheetah)",
    pcrId: "patrol-pandri-04",
  },
  {
    id: "saraswati-nagar-ps",
    type: "station",
    code: "PS-SRW",
    name: "सरस्वती नगर पुलिस थाना",
    nameEn: "Saraswati Nagar Police Station",
    areaId: "saraswati-nagar",
    lat: 21.25400,
    lng: 81.58800,
    phone: "0771-4287155",
    emergencyPhone: "112 / 0771-4287155",
    inCharge: "Ins. M. L. Patel",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "आमानाका चौक, एनआईटी रायपुर, यूनिवर्सिटी क्षेत्र, समता कॉलोनी",
    jurisdictionEn: "Amanaka Chowk, NIT Raipur, University Area, Samta Colony",
    address: "यूनिवर्सिटी गेट 2 के सामने, सरस्वती नगर, रायपुर",
    addressEn: "Opp. University Gate 2, Saraswati Nagar, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-05 (Saraswati Falcon)",
    pcrId: "patrol-saraswati-05",
  },
  {
    id: "tikrapara-ps",
    type: "station",
    code: "PS-TKP",
    name: "टिकरापारा पुलिस थाना",
    nameEn: "Tikrapara Police Station",
    areaId: "tikrapara",
    lat: 21.22400,
    lng: 81.65200,
    phone: "0771-4287166",
    emergencyPhone: "112 / 0771-4287166",
    inCharge: "Ins. D. S. Thakur",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "पुरानी धमतरी रोड, पचपेड़ी नाका, संतोषी नगर, सेजबहार रिंग रोड 1",
    jurisdictionEn: "Old Dhamtari Road, Pachpedi Naka, Santoshi Nagar, Sejbahar Ring Road 1",
    address: "पचपेड़ी नाका चौक के पास, टिकरापारा, रायपुर",
    addressEn: "Near Pachpedi Naka Chowk, Tikrapara, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-06 (Tikrapara Panther)",
    pcrId: "patrol-tikrapara-06",
  },
  {
    id: "tatibandh-ps",
    type: "station",
    code: "OP-TTB",
    name: "तातीबंध पुलिस थाना / चौकी",
    nameEn: "Tatibandh Police Outpost",
    areaId: "tatibandh",
    lat: 21.25672,
    lng: 81.57344,
    phone: "0771-4287177",
    emergencyPhone: "112 / 0771-4287177",
    inCharge: "Sub-Ins. P. K. Sahu",
    inChargeRank: "Outpost In-Charge (चौकी प्रभारी)",
    inChargeRankHi: "चौकी प्रभारी (उप-निरीक्षक)",
    jurisdiction: "तातीबंध चौक, एम्स अस्पताल, एनएच-53 हाईवे बाइपास, भनपुरी मोड़",
    jurisdictionEn: "Tatibandh Chowk, AIIMS Hospital, NH-53 Highway Bypass, Bhanpuri Turn",
    address: "एनएच-53 फ्लाईओव्हर चौक, तातीबंध, रायपुर",
    addressEn: "NH-53 Flyover Chowk, Tatibandh, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-07 (Tatibandh Highway Guard)",
    pcrId: "patrol-tatibandh-07",
  },
  {
    id: "ganj-ps",
    type: "station",
    code: "PS-GNJ",
    name: "गंज पुलिस थाना (रेलवे स्टेशन)",
    nameEn: "Ganj Police Station (Railway Station)",
    areaId: "ganj",
    lat: 21.25780,
    lng: 81.63029,
    phone: "0771-4287188",
    emergencyPhone: "112 / 0771-4287188",
    inCharge: "Ins. R. S. Baghel",
    inChargeRank: "Station House Officer (SHO)",
    inChargeRankHi: "थाना प्रभारी (टी.आई.)",
    jurisdiction: "रायपुर रेलवे जंक्शन, स्टेशन रोड, फाफाडीह, रामसागर पारा",
    jurisdictionEn: "Raipur Railway Junction, Station Road, Fafadih, Ramsagar Para",
    address: "रेलवे स्टेशन मुख्य निकास मार्ग, गंजपारा, रायपुर",
    addressEn: "Railway Station Main Exit Road, Ganjpara, Raipur",
    status: "open_24x7",
    statusLabel: { hi: "24x7 खुला", en: "24x7 Active" },
    assignedPatrol: "PCR-08 (Ganj Station Guard)",
    pcrId: "patrol-ganj-08",
  },
];

// Live Patrolling Units (PCR Vans, Highway Patrols & Motorcycle Squads)
export const PATROL_UNITS = [
  {
    id: "patrol-kotwali-01",
    type: "patrol",
    vehicleCategory: "pcr_van",
    code: "PCR-01",
    callSign: "TIGER-1",
    vehicleNumber: "CG 04 PC 1001",
    name: "कोतवाली टाइगर पेट्रोल (PCR-01)",
    nameEn: "Kotwali Tiger Patrol (PCR-01)",
    areaId: "kotwali",
    areaName: "सेंट्रल सेक्टर",
    areaNameEn: "Central Sector",
    stationId: "kotwali-ps",
    stationName: "कोतवाली पुलिस थाना",
    stationNameEn: "Kotwali Police Station",
    vehicleType: "Tata Xenon 4x4 Mobile PCR",
    officer: "ASI S. Baghel",
    officerRank: "Assistant Sub-Inspector (ASI)",
    officerRankHi: "सहा. उप-निरीक्षक (ASI)",
    phone: "0771-4287111",
    mobile: "94791-90001",
    sector: "जयस्तंभ चौक · मालवीय रोड · गोल बाज़ार",
    sectorEn: "Jaistambh Chowk · Malviya Road · Gol Bazar",
    lat: 21.24480,
    lng: 81.63350,
    status: "on_patrol",
    statusLabel: { hi: "सक्रिय गश्त (Active)", en: "Active Patrol" },
    speed: "22 km/h",
    fuelBattery: "88%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.24480, 81.63350],
      [21.24650, 81.63420],
      [21.24320, 81.63680],
      [21.24150, 81.63290],
    ],
  },
  {
    id: "patrol-kotwali-bike-01",
    type: "patrol",
    vehicleCategory: "bike_squad",
    code: "CHEETAH-01",
    callSign: "CHEETAH-KTW",
    vehicleNumber: "CG 04 PC 1002",
    name: "कोतवाली चीता बाइक स्क्वाड (CHEETAH-01)",
    nameEn: "Kotwali Cheetah Bike Squad (CHEETAH-01)",
    areaId: "kotwali",
    areaName: "सेंट्रल सेक्टर",
    areaNameEn: "Central Sector",
    stationId: "kotwali-ps",
    stationName: "कोतवाली पुलिस थाना",
    stationNameEn: "Kotwali Police Station",
    vehicleType: "Bajaj Pulsar 250 Twin Patrol",
    officer: "HC Dinesh Sahu",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287111",
    mobile: "94791-90011",
    sector: "सदर बाज़ार · चिकनी मंदिर लेन · एमजी रोड",
    sectorEn: "Sadar Bazar · Chikni Mandir Lane · MG Road",
    lat: 21.24220,
    lng: 81.63800,
    status: "on_patrol",
    statusLabel: { hi: "मार्केट गश्त (Active)", en: "Market Patrol" },
    speed: "16 km/h",
    fuelBattery: "92%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.24220, 81.63800],
      [21.24410, 81.63950],
      [21.24100, 81.63600],
    ],
  },
  {
    id: "patrol-civillines-02",
    type: "patrol",
    vehicleCategory: "pcr_van",
    code: "PCR-02",
    callSign: "HAWK-1",
    vehicleNumber: "CG 04 PC 1003",
    name: "सिविल लाइन्स हॉक पेट्रोल (PCR-02)",
    nameEn: "Civil Lines Hawk Patrol (PCR-02)",
    areaId: "civil-lines",
    areaName: "वीआईपी सेक्टर",
    areaNameEn: "VIP Sector",
    stationId: "civil-lines-ps",
    stationName: "सिविल लाइन्स पुलिस थाना",
    stationNameEn: "Civil Lines Police Station",
    vehicleType: "Mahindra Bolero Mobile Van",
    officer: "HC Ramesh Sahu",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287122",
    mobile: "94791-90002",
    sector: "घड़ी चौक · कलेक्टोरेट · राजभवन · शांति नगर",
    sectorEn: "Ghadi Chowk · Collectorate · Raj Bhavan · Shanti Nagar",
    lat: 21.24650,
    lng: 81.64100,
    status: "on_patrol",
    statusLabel: { hi: "वीआईपी सुरक्षा गश्त", en: "VIP Security Patrol" },
    speed: "26 km/h",
    fuelBattery: "79%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.24650, 81.64100],
      [21.24800, 81.64400],
      [21.24400, 81.64650],
      [21.24250, 81.64200],
    ],
  },
  {
    id: "patrol-civillines-erv-02",
    type: "patrol",
    vehicleCategory: "erv",
    code: "ERV-02",
    callSign: "EAGLE-SEC",
    vehicleNumber: "CG 04 PC 1004",
    name: "सिविल लाइन्स इमरजेंसी रिस्पॉन्स व्हीकल (ERV-02)",
    nameEn: "Civil Lines Emergency Response Vehicle (ERV-02)",
    areaId: "civil-lines",
    areaName: "वीआईपी सेक्टर",
    areaNameEn: "VIP Sector",
    stationId: "civil-lines-ps",
    stationName: "सिविल लाइन्स पुलिस थाना",
    stationNameEn: "Civil Lines Police Station",
    vehicleType: "Toyota Innova Emergency Command Van",
    officer: "SI Anurag Shukla",
    officerRank: "Sub-Inspector (SI)",
    officerRankHi: "उप-निरीक्षक (SI)",
    phone: "0771-4287122",
    mobile: "94791-90012",
    sector: "कमिश्नर कार्यालय · राजभवन एवेन्यू · पीडब्ल्यूडी चौक",
    sectorEn: "Commissioner HQ · Raj Bhavan Ave · PWD Chowk",
    lat: 21.24820,
    lng: 81.64750,
    status: "responding",
    statusLabel: { hi: "इमरजेंसी अलर्ट रिस्पॉन्स", en: "Emergency Responding" },
    speed: "38 km/h",
    fuelBattery: "85%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.24820, 81.64750],
      [21.24500, 81.64900],
      [21.24300, 81.64400],
    ],
  },
  {
    id: "patrol-telibandha-03",
    type: "patrol",
    vehicleCategory: "interceptor",
    code: "PCR-03",
    callSign: "EAGLE-1",
    vehicleNumber: "CG 04 PC 1005",
    name: "तेलीबांधा ईगल हाईवे पेट्रोल (PCR-03)",
    nameEn: "Telibandha Eagle Highway Patrol (PCR-03)",
    areaId: "telibandha",
    areaName: "ईस्ट सेक्टर",
    areaNameEn: "East Sector",
    stationId: "telibandha-ps",
    stationName: "तेलीबांधा पुलिस थाना",
    stationNameEn: "Telibandha Police Station",
    vehicleType: "Scorpio High-Speed Interceptor Van",
    officer: "ASI M. K. Verma",
    officerRank: "Assistant Sub-Inspector (ASI)",
    officerRankHi: "सहा. उप-निरीक्षक (ASI)",
    phone: "0771-4287133",
    mobile: "94791-90003",
    sector: "मरीन ड्राइव · वीआईपी रोड · तेलीबांधा एक्सप्रेसवे",
    sectorEn: "Marine Drive · VIP Road · Telibandha Expressway",
    lat: 21.23450,
    lng: 81.66800,
    status: "on_patrol",
    statusLabel: { hi: "हाईवे गश्त (Active)", en: "Highway Patrol" },
    speed: "35 km/h",
    fuelBattery: "94%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.23450, 81.66800],
      [21.23700, 81.67400],
      [21.23100, 81.67900],
      [21.22800, 81.66500],
    ],
  },
  {
    id: "patrol-telibandha-bike-03",
    type: "patrol",
    vehicleCategory: "bike_squad",
    code: "CHEETAH-03",
    callSign: "MARINE-GUARD",
    vehicleNumber: "CG 04 PC 1006",
    name: "मरीन ड्राइव लेक पेट्रोल बाइक (CHEETAH-03)",
    nameEn: "Marine Drive Lake Patrol Bike (CHEETAH-03)",
    areaId: "telibandha",
    areaName: "ईस्ट सेक्टर",
    areaNameEn: "East Sector",
    stationId: "telibandha-ps",
    stationName: "तेलीबांधा पुलिस थाना",
    stationNameEn: "Telibandha Police Station",
    vehicleType: "Royal Enfield Bullet Police Patrol",
    officer: "Constable Vikas Kashyap",
    officerRank: "Police Constable (PC)",
    officerRankHi: "आरक्षक (PC)",
    phone: "0771-4287133",
    mobile: "94791-90013",
    sector: "मरीन ड्राइव वॉकवे · तेलीबांधा तालाब घाट · लाभांडी मोड़",
    sectorEn: "Marine Drive Walkway · Lake Promenade · Labhandi",
    lat: 21.23800,
    lng: 81.66500,
    status: "on_patrol",
    statusLabel: { hi: "झील तट गश्त", en: "Lake Area Patrol" },
    speed: "15 km/h",
    fuelBattery: "90%",
    shift: "Evening Peak Shift",
    waypoints: [
      [21.23800, 81.66500],
      [21.23550, 81.66200],
      [21.23950, 81.66900],
    ],
  },
  {
    id: "patrol-pandri-04",
    type: "patrol",
    vehicleCategory: "bike_squad",
    code: "PCR-04",
    callSign: "CHEETAH-4",
    vehicleNumber: "CG 04 PC 1007",
    name: "पंडरी चीता स्क्वाड (PCR-04)",
    nameEn: "Pandri Cheetah Squad (PCR-04)",
    areaId: "pandri",
    areaName: "कमर्शियल सेक्टर",
    areaNameEn: "Commercial Sector",
    stationId: "pandri-ps",
    stationName: "पंडरी पुलिस थाना",
    stationNameEn: "Pandri Police Station",
    vehicleType: "Bajaj Pulsar Dual Traffic Squad",
    officer: "HC Rajesh Netam",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287144",
    mobile: "94791-90004",
    sector: "कपड़ा बाज़ार · सिटी मॉल · मोवा ओवरब्रिज",
    sectorEn: "Cloth Market · City Center Mall · Mowa Overbridge",
    lat: 21.25100,
    lng: 81.64500,
    status: "on_patrol",
    statusLabel: { hi: "सक्रिय गश्त (Active)", en: "Active Patrol" },
    speed: "18 km/h",
    fuelBattery: "76%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.25100, 81.64500],
      [21.25450, 81.64900],
      [21.25600, 81.64300],
      [21.24900, 81.64100],
    ],
  },
  {
    id: "patrol-saraswati-05",
    type: "patrol",
    vehicleCategory: "pcr_van",
    code: "PCR-05",
    callSign: "FALCON-1",
    vehicleNumber: "CG 04 PC 1008",
    name: "सरस्वती फाल्कन पेट्रोल (PCR-05)",
    nameEn: "Saraswati Falcon Patrol (PCR-05)",
    areaId: "saraswati-nagar",
    areaName: "वेस्ट सेक्टर",
    areaNameEn: "West Sector",
    stationId: "saraswati-nagar-ps",
    stationName: "सरस्वती नगर पुलिस थाना",
    stationNameEn: "Saraswati Nagar Police Station",
    vehicleType: "Mahindra Bolero Mobile Van",
    officer: "ASI Deepesh Dewangan",
    officerRank: "Assistant Sub-Inspector (ASI)",
    officerRankHi: "सहा. उप-निरीक्षक (ASI)",
    phone: "0771-4287155",
    mobile: "94791-90005",
    sector: "एनआईटी रायपुर · समता कॉलोनी · यूनिवर्सिटी रोड",
    sectorEn: "NIT Raipur · Samta Colony · University Road",
    lat: 21.24900,
    lng: 81.59500,
    status: "on_patrol",
    statusLabel: { hi: "कैंपस गश्त (Active)", en: "Campus Patrol" },
    speed: "25 km/h",
    fuelBattery: "82%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.24900, 81.59500],
      [21.25200, 81.59900],
      [21.24600, 81.59000],
      [21.24400, 81.59300],
    ],
  },
  {
    id: "patrol-tikrapara-06",
    type: "patrol",
    vehicleCategory: "pcr_van",
    code: "PCR-06",
    callSign: "PANTHER-1",
    vehicleNumber: "CG 04 PC 1009",
    name: "टिकरापारा पैंथर पेट्रोल (PCR-06)",
    nameEn: "Tikrapara Panther Patrol (PCR-06)",
    areaId: "tikrapara",
    areaName: "साउथ सेक्टर",
    areaNameEn: "South Sector",
    stationId: "tikrapara-ps",
    stationName: "टिकरापारा पुलिस थाना",
    stationNameEn: "Tikrapara Police Station",
    vehicleType: "Tata Xenon 4x4 Heavy PCR",
    officer: "HC O. P. Yadav",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287166",
    mobile: "94791-90006",
    sector: "पचपेड़ी नाका · संतोषी नगर · पुरानी धमतरी रोड",
    sectorEn: "Pachpedi Naka · Santoshi Nagar · Old Dhamtari Rd",
    lat: 21.22100,
    lng: 81.64800,
    status: "on_patrol",
    statusLabel: { hi: "रिंग रोड गश्त (Active)", en: "Ring Road Patrol" },
    speed: "30 km/h",
    fuelBattery: "89%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.22100, 81.64800],
      [21.22450, 81.65400],
      [21.21800, 81.65600],
      [21.21600, 81.64500],
    ],
  },
  {
    id: "patrol-tatibandh-07",
    type: "patrol",
    vehicleCategory: "interceptor",
    code: "PCR-07",
    callSign: "GUARD-1",
    vehicleNumber: "CG 04 PC 1010",
    name: "तातीबंध हाईवे गार्ड पेट्रोल (PCR-07)",
    nameEn: "Tatibandh Highway Guard Patrol (PCR-07)",
    areaId: "tatibandh",
    areaName: "हाईवे सेक्टर",
    areaNameEn: "Highway Sector",
    stationId: "tatibandh-ps",
    stationName: "तातीबंध पुलिस चौकी",
    stationNameEn: "Tatibandh Police Outpost",
    vehicleType: "Highway Emergency Response Interceptor",
    officer: "ASI B. R. Kurre",
    officerRank: "Assistant Sub-Inspector (ASI)",
    officerRankHi: "सहा. उप-निरीक्षक (ASI)",
    phone: "0771-4287177",
    mobile: "94791-90007",
    sector: "तातीबंध चौक · एम्स अस्पताल · एनएच-53 बाइपास",
    sectorEn: "Tatibandh Chowk · AIIMS Hospital · NH-53 Bypass",
    lat: 21.25800,
    lng: 81.57900,
    status: "on_patrol",
    statusLabel: { hi: "हाईवे गश्त (Active)", en: "Highway Patrol" },
    speed: "28 km/h",
    fuelBattery: "91%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.25800, 81.57900],
      [21.26100, 81.57200],
      [21.25500, 81.56800],
      [21.25300, 81.57700],
    ],
  },
  {
    id: "patrol-tatibandh-erv-07",
    type: "patrol",
    vehicleCategory: "erv",
    code: "ERV-07",
    callSign: "AIIMS-LIFELINE",
    vehicleNumber: "CG 04 PC 1011",
    name: "एम्स हॉस्पिटल कॉरिडोर ERV (ERV-07)",
    nameEn: "AIIMS Hospital Corridor ERV (ERV-07)",
    areaId: "tatibandh",
    areaName: "हाईवे सेक्टर",
    areaNameEn: "Highway Sector",
    stationId: "tatibandh-ps",
    stationName: "तातीबंध पुलिस चौकी",
    stationNameEn: "Tatibandh Police Outpost",
    vehicleType: "Mahindra Scorpio Traffic Pilot",
    officer: "HC Mahendra Dhruw",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287177",
    mobile: "94791-90017",
    sector: "एम्स मुख्य द्वार · ग्रीन कॉरिडोर रूट · रिंग रोड जंक्शन",
    sectorEn: "AIIMS Main Gate · Green Corridor Route · Ring Rd",
    lat: 21.25600,
    lng: 81.57100,
    status: "standby",
    statusLabel: { hi: "स्टैंडबाय (Standby)", en: "Standby / Pilot Ready" },
    speed: "0 km/h",
    fuelBattery: "98%",
    shift: "Emergency Green Corridor Ready",
    waypoints: [
      [21.25600, 81.57100],
      [21.25850, 81.57400],
    ],
  },
  {
    id: "patrol-ganj-08",
    type: "patrol",
    vehicleCategory: "bike_squad",
    code: "PCR-08",
    callSign: "STATION-1",
    vehicleNumber: "CG 04 PC 1012",
    name: "गंज स्टेशन गार्ड पेट्रोल (PCR-08)",
    nameEn: "Ganj Station Guard Patrol (PCR-08)",
    areaId: "ganj",
    areaName: "स्टेशन सेक्टर",
    areaNameEn: "Station Sector",
    stationId: "ganj-ps",
    stationName: "गंज पुलिस थाना",
    stationNameEn: "Ganj Police Station",
    vehicleType: "Rapid Action Traffic Bike Squad",
    officer: "HC Vijay Markam",
    officerRank: "Head Constable (HC)",
    officerRankHi: "प्रधान आरक्षक (HC)",
    phone: "0771-4287188",
    mobile: "94791-90008",
    sector: "रायपुर रेलवे स्टेशन · स्टेशन रोड · फाफाडीह चौक",
    sectorEn: "Raipur Railway Station · Station Road · Fafadih Chowk",
    lat: 21.25600,
    lng: 81.62800,
    status: "on_patrol",
    statusLabel: { hi: "सक्रिय गश्त (Active)", en: "Active Patrol" },
    speed: "20 km/h",
    fuelBattery: "84%",
    shift: "24x7 Day/Night Shift",
    waypoints: [
      [21.25600, 81.62800],
      [21.25800, 81.63200],
      [21.25400, 81.62500],
    ],
  },
];

// Haversine distance calculation in km
export function calculateDistance(lat1, lon1, lat2, lon2) {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

// Find nearest police station
export function findNearestPoliceStation(lat, lng, stations = POLICE_STATIONS) {
  const list = stations && stations.length > 0 ? stations : POLICE_STATIONS;
  let nearest = list[0];
  let minDistance = Infinity;

  list.forEach((station) => {
    const dist = calculateDistance(lat, lng, station.lat, station.lng);
    if (dist < minDistance) {
      minDistance = dist;
      nearest = { ...station, distanceKm: dist.toFixed(2), distanceNum: dist };
    }
  });

  return nearest;
}

// Find nearest patrolling unit
export function findNearestPatrolUnit(lat, lng, patrols = PATROL_UNITS) {
  const list = patrols && patrols.length > 0 ? patrols : PATROL_UNITS;
  let nearest = list[0];
  let minDistance = Infinity;

  list.forEach((patrol) => {
    const dist = calculateDistance(lat, lng, patrol.lat, patrol.lng);
    if (dist < minDistance) {
      minDistance = dist;
      nearest = { ...patrol, distanceKm: dist.toFixed(2), distanceNum: dist };
    }
  });

  return nearest;
}

// Get all police stations sorted by distance from given coordinates
export function getPoliceStationsWithDistance(lat, lng) {
  return POLICE_STATIONS.map((stn) => {
    const dist = calculateDistance(lat, lng, stn.lat, stn.lng);
    return {
      ...stn,
      distanceKm: dist.toFixed(2),
      distanceNum: dist,
    };
  }).sort((a, b) => a.distanceNum - b.distanceNum);
}

// Get all patrol units sorted by distance from given coordinates
export function getPatrolUnitsWithDistance(lat, lng) {
  return PATROL_UNITS.map((p) => {
    const dist = calculateDistance(lat, lng, p.lat, p.lng);
    return {
      ...p,
      distanceKm: dist.toFixed(2),
      distanceNum: dist,
    };
  }).sort((a, b) => a.distanceNum - b.distanceNum);
}

// Get combined list of stations and patrols sorted by proximity
export function getAllPoliceWithDistance(lat, lng) {
  const stations = getPoliceStationsWithDistance(lat, lng);
  const patrols = getPatrolUnitsWithDistance(lat, lng);
  return [...stations, ...patrols].sort((a, b) => a.distanceNum - b.distanceNum);
}
